spring.application.name: Interview


server:
  port: 8080
#Configuring DB Connection
spring:
  datasource:
    url: jdbc:postgresql://db:5432/db
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#Enable actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
